name: Generate Snake Animation

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 4 * * *" 
    
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
      - name: Debug - Check generated files
        run: |
          ls -lah dist
          cat dist/github-snake.svg
      - name: Commit and Push Snake Animation
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Updated snake animation"
          file_pattern: dist/github-snake*.svg
